apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: stream-service
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    authorization:
      type: simple
    config:
      inter.broker.protocol.version: '2.8'
      log.message.format.version: '2.8'
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
      - name: tls
        port: 9093
        tls: true
        type: internal
      - authentication:
          type: scram-sha-512
        name: external
        port: 9094
        tls: true
        type: route
    replicas: 3
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
    version: 2.8.0
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
