apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  labels:
    strimzi.io/cluster: stream-service
  name: subscription-consumer
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
      - host: '*'
        operation: Read
        resource:
          name: machinerysubscription
          patternType: literal
          type: topic
        type: allow
      - host: '*'
        operation: Describe
        resource:
          name: machinerysubscription
          patternType: literal
          type: topic
        type: allow
      - host: '*'
        operation: Read
        resource:
          name: plant-manager
          patternType: literal
          type: group
        type: allow
    type: simple
