name: manufacturing-datacenter-install

########## mongo ##########
mongo:
  path: "/var/hpvolumes/mongodb"
  storageCapacity: 5Gi
  MONGO_INITDB_ROOT_USERNAME: qiotroot
  MONGO_INITDB_ROOT_PASSWORD: qiotrootpassword
  MONGODB_ADMIN_PASSWORD: qiotrootpassword
  MONGODB_DATABASE: qiot_manufacturing
  MONGODB_PASSWORD: qiotmanufacturingpassword
  MONGODB_USER: qiotmanufacturing
  
########## Influxdb2 ##########
influxdb2:
  enabled: True
  adminUser:
    create: true
    organization: "qiot"
    bucket: "manufacturing"
    user: "qiotmanufacturing"
    retention_policy: "0s"
    password: "qiotmanufacturingpassword"
    token: "qiotmanufacturinginfluxdbtoken"
  pdb:
    create: False

########## postgresql ##########
postgresql:
  path: "/var/hpvolumes/postgresql"
  storageCapacity: 5Gi
  POSTGRESQL_DATABASE: qiot_manufacturing
  POSTGRESQL_PASSWORD: qiotmanufacturingpassword
  POSTGRESQL_USER: qiotmanufacturing
