apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-collector-service
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: event-collector-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/event-collector-service/event-collector-service-cm.yaml") . | sha256sum }}
      labels:
        app: event-collector-service
        deploymentconfig: event-collector-service
    spec:
      containers:
      - image: quay.io/qiotmanufacturing/datacenter-event-collector-jvm
        imagePullPolicy: Always
        name: event-collector-service
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /deployments/config
          name: event-collector-service
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: event-collector-service
        name: event-collector-service
