# Default values for issuer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

baseDomain: qiot-project.io
wildcardDomain: ""

issuer:
  vault:
    namespace: vault
    secret: vault-vault-bootstrap
    server: https://vault-internal.hashicorp.svc.cluster.local:8200
    image:
      repository: "registry.connect.redhat.com/hashicorp/vault"
      tag: "1.11.3-ubi"
